CREATE DATABASE customer;

USE customer;

CREATE TABLE customer_behaviors (
    customer_id INT PRIMARY KEY,
    age INT,
    gender VARCHAR(10),
    item_purchased VARCHAR(255),
    category VARCHAR(100),
    purchase_amount INT,
    location VARCHAR(100),
    size VARCHAR(20),
    color VARCHAR(50),
    season VARCHAR(20),
    review_rating FLOAT,
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(50),
    previous_purchases INT,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50),
    age_group VARCHAR(20),
    purchase_frequency_days INT
);



SELECT * FROM customer.customer_behaviors LIMIT 10;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT Sum(purchase_amount) as Revenue, gender
FROM customer.customer_behaviors
GROUP BY gender
ORDER BY Revenue;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount 
FROM customer.customer_behaviors
WHERE discount_applied = "Yes" and purchase_amount >= (SELECT AVG(purchase_amount) FROM customer.customer_behaviors);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as rating 
FROM customer.customer_behaviors 
GROUP BY item_purchased
ORDER BY rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT ROUND(AVG(purchase_amount),2) , shipping_type
FROM customer.customer_behaviors
WHERE shipping_type in ("Express" , "Standard")
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, COUNT(customer_id) as total_customer,
ROUND(AVG(purchase_amount),2) as average_revenue, ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer.customer_behaviors
GROUP BY subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased as product,
ROUND(SUM(CASE WHEN discount_applied = "Yes" THEN 1 ELSE 0 END) * 100/ COUNT(*),2) as discount_apply
FROM customer.customer_behaviors
GROUP BY product
ORDER BY discount_apply DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type as
(SELECT customer_id, 
CASE 
	WHEN previous_purchases = 1 THEN "NEW"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal" END as segment
FROM customer.customer_behaviors    
GROUP BY customer_id)

SELECT segment, COUNT(*) as "No. of Customer"
FROM customer_type
GROUP BY segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts as 
(SELECT category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category order by COUNT(customer_id) DESC) as item_ranks
FROM customer.customer_behaviors
GROUP BY category, item_purchased)

SELECT item_ranks , category, item_purchased, total_orders
FROM item_counts
WHERE item_ranks <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as "No. of Customer"
FROM customer.customer_behaviors
WHERE previous_purchases >5
GROUP BY subscription_Status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) as Revenue
FROM customer.customer_behaviors
GROUP BY age_group
